In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Dataset for Data Analytics.csv")
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [3]:
df.shape

(1200, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [5]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

In [8]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [9]:
df['CouponCode'] = df['CouponCode'].fillna("Not Used")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [12]:
df.dtypes

OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

In [13]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [14]:
df['Date']  = pd.to_datetime(df['Date'])

In [15]:
(df['Quantity']*df['UnitPrice'] == df['TotalPrice']).all()

np.False_

In [16]:
wrong_price = df[df['Quantity'] * df['UnitPrice']!= df['TotalPrice']]
wrong_price

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
10,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
11,ORD200011,2024-02-17,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
32,ORD200032,2023-05-01,C12388,Tablet,5,536.72,830 Main St,Cash,Delivered,TRK99261395,10,Not Used,Email,2683.60
39,ORD200039,2025-02-27,C96664,Printer,3,256.46,666 Main St,Credit Card,Delivered,TRK85508960,4,SAVE10,Referral,769.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,ORD201166,2023-07-31,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
1175,ORD201175,2024-09-10,C62512,Printer,3,91.74,368 Main St,Debit Card,Returned,TRK24139954,8,FREESHIP,Referral,275.22
1189,ORD201189,2024-08-17,C96136,Tablet,5,389.22,149 Main St,Cash,Cancelled,TRK60856682,7,Not Used,Referral,1946.10
1192,ORD201192,2024-02-28,C72007,Chair,3,432.85,999 Main St,Online,Pending,TRK16240916,4,Not Used,Instagram,1298.55
1194,ORD201194,2023-11-19,C29885,Printer,3,189.44,725 Main St,Cash,Pending,TRK62067865,4,FREESHIP,Email,568.32

In [17]:
wrong_price[['Quantity','UnitPrice','TotalPrice']].head(10)

    Quantity  UnitPrice  TotalPrice
2          5     550.68     2753.40
10         5     625.97     3129.85
11         3      49.14      147.42
32         5     536.72     2683.60
39         3     256.46      769.38
41         3     611.45     1834.35
43         3     499.21     1497.63
55         3     344.40     1033.20
56         3     479.21     1437.63
64         3     130.61      391.83

In [19]:
((df['Quantity'] * df['UnitPrice']).round(2) == df['TotalPrice'].round(2)).all()

np.True_

In [23]:
print(df[['Quantity','UnitPrice', 'TotalPrice']].describe())

          Quantity    UnitPrice   TotalPrice
count  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750  1053.968300
std       1.407557   197.177146   819.856558
min       1.000000    11.390000    11.390000
25%       2.000000   186.062500   410.520000
50%       3.000000   364.210000   823.615000
75%       4.000000   521.570000  1578.475000
max       5.000000   699.930000  3456.400000

In [28]:
print(df['OrderStatus'].unique())
print(df['PaymentMethod'].value_counts())
print(df['ReferralSource'].value_counts())

['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']
PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64
ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [30]:
#removing low analytical value columns :
columns = ['OrderID','TrackingNumber','ShippingAddress']
df = df.drop(columns=columns)

In [31]:
df

,Date,CustomerID,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,2023-01-04,C72649,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10
1,2024-08-23,C75739,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70
2,2024-02-27,C81728,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40
3,2023-10-15,C33540,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19
4,2025-05-08,C81840,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-06-20,C21126,Desk,1,107.04,Credit Card,Cancelled,6,FREESHIP,Google,107.04
1196,2024-03-04,C20095,Monitor,2,662.53,Online,Cancelled,5,Not Used,Facebook,1325.06
1197,2023-07-13,C79674,Tablet,2,436.84,Online,Delivered,2,FREESHIP,Instagram,873.68
1198,2024-08-22,C64753,Chair,4,262.52,Debit Card,Cancelled,4,WINTER15,Instagram,1050.08
1199,2023-06-11,C57502,Tablet,4,560.58,Gift Card,Returned,6,SAVE10,Referral,2242.32

In [32]:
df.columns

Index(['Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'PaymentMethod', 'OrderStatus', 'ItemsInCart', 'CouponCode',
       'ReferralSource', 'TotalPrice'],
      dtype='object')

In [34]:
#standardizing text columns:

text_columns = ['Product' , 'PaymentMethod' , 'OrderStatus' , 'CouponCode' , 'ReferralSource']
for cols in text_columns:
    df[cols] = df[cols].astype(str).str.strip()

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1200 non-null   datetime64[ns]
 1   CustomerID      1200 non-null   object
 2   Product         1200 non-null   object
 3   Quantity        1200 non-null   int64
 4   UnitPrice       1200 non-null   float64
 5   PaymentMethod   1200 non-null   object
 6   OrderStatus     1200 non-null   object
 7   ItemsInCart     1200 non-null   int64
 8   CouponCode      1200 non-null   object
 9   ReferralSource  1200 non-null   object
 10  TotalPrice      1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 103.3+ KB

In [36]:
df.to_csv("Cleaned_dataset.csv" , index=False)

In [37]:
df.isnull().sum()

Date              0
CustomerID        0
Product           0
Quantity          0
UnitPrice         0
PaymentMethod     0
OrderStatus       0
ItemsInCart       0
CouponCode        0
ReferralSource    0
TotalPrice        0
dtype: int64